version: "3"

services:
  db:
    container_name: mysql_spring
    image: mysql:latest
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sogong
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql-init-file:/docker-entrypoint-initdb.d/
      - ./db/data:/var/lib/mysql
